"""gamemode: add seetakki

Revision ID: d16e38b4060c
Revises: 178873984b22
Create Date: 2025-08-22 14:48:08.023648

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d16e38b4060c"
down_revision: str | Sequence[str] | None = "178873984b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "rank_history",
        "mode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    op.alter_column(
        "rank_top",
        "mode",
        existing_type=mysql.ENUM(
            "OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX", "SENTAKKI"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "rank_history",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    op.alter_column(
        "rank_top",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX"),
        nullable=False,
    )
    # ### end Alembic commands ###
